npm install express
npm install firebase
npm install axios
npm install cors
npm install pug 
pip3 install tldextract
pip3 install PyQt5
pip3 install requests
pip3 install bs4
pip3 install mitmproxy
pip3 install pymongo
